// [GENERATED BY SYSTEM ZERO ENGINE]
// Source: zero_task_manifest.yaml (Engine: useTasks)

import { useState, useCallback } from 'react';
import type { TTask } from '../types/task';
import { TaskStatus } from '../types/task';

export const useTasks = () => {
    const [tasks, setTasks] = useState<TTask[]>([]);

    const addTask = useCallback((title: string, description: string) => {
        const newTask: TTask = {
            id: crypto.randomUUID(),
            title,
            description,
            status: TaskStatus.PENDING,
            createdAt: Date.now(),
        };
        setTasks(prev => [newTask, ...prev]);
    }, []);

    const toggleTask = useCallback((id: string) => {
        setTasks(prev => prev.map(task =>
            task.id === id
                ? { ...task, status: task.status === TaskStatus.COMPLETED ? TaskStatus.PENDING : TaskStatus.COMPLETED }
                : task
        ));
    }, []);

    const deleteTask = useCallback((id: string) => {
        setTasks(prev => prev.filter(task => task.id !== id));
    }, []);

    return {
        tasks,
        addTask,
        toggleTask,
        deleteTask,
    };
};
