// [GENERATED BY SYSTEM ZERO ENGINE]
// Source: zero_task_manifest.yaml (Schema: Task)

export const TaskStatus = {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
} as const;

export type TaskStatusType = typeof TaskStatus[keyof typeof TaskStatus];

export interface TTask {
    id: string;
    title: string;
    description: string;
    status: TaskStatusType;
    createdAt: number;
}
